server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    # password: your_redis_password ← 설정된 경우 추가

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dev.crudproject01.domain
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: your_jwt_secret_key
  expiration: 3600000 # 1시간 (밀리초 단위)

logging:
  level:
    root: INFO
    com.dev.crudproject01: DEBUG
